services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: frontair
      MARIADB_PASSWORD: mypassword
      MARIADB_DATABASE: frontair
    ports:
      - 13306:3306
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
    db:
