name: Build & Deployment

on:
  push:
    branches: [ 'main' ]
  #    paths: [ 'FrontAir/**' ]
  pull_request:
    branches: [ 'main' ]
#    paths: [ 'FrontAir/**' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm install
        working-directory: FrontAir

      - name: Verify node version
        run: node -v
        
      - name: Verify npm version
        run: npm -v

      - name: Linter
        run: npm run lint
        working-directory: FrontAir

#      - name: Run tests
#        run: npm run test
#        working-directory: FrontAir

      - name: Build the application
        run: npm run build-only
        working-directory: FrontAir

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: FrontAir/dist

  #  release:
  #    runs-on: ubuntu-latest
  #    needs: build
  #    steps:
  #      - name: Download build artifacts
  #        uses: actions/download-artifact@v3
  #        with:
  #          name: dist-artifact
  #
  #      - name: Create a Tag
  #        id: tag_creation
  #        run: |
  #          TAG=$(date +%Y%m%d%H%M%S)
  #          echo "Creating tag $TAG"
  #          git tag $TAG
  #          git push origin $TAG
  #          echo "::set-output name=TAG::$TAG"
  #
  #      - name: Create GitHub Release
  #        id: create_release
  #        uses: actions/create-release@v1
  #        with:
  #          tag_name: ${{ steps.tag_creation.outputs.TAG }}
  #          release_name: "Release ${{ steps.tag_creation.outputs.TAG }}"
  #          body: "Automated release of Vue.js application."
  #          draft: false
  #          prerelease: false
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
#    needs: [ 'build', 'release' ]
    needs: [ 'build' ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm install
        working-directory: FrontAir

      - name: Build project
        run: npm run build-only
        working-directory: FrontAir

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
        working-directory: FrontAir
