name: Vue.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DAY_OF_THE_WEEK: Monday

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Greeting: Hey

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Say Hey to Pepijn if it is Monday
        if: ${{ env.DAY_OF_THE_WEEK == 'Monday' }}
        run:  echo "$Greeting $First_Name, today is $DAY_OF_THE_WEEK!"
        env:
          First_Name: Pepijn

      - name: Install dependencies
        run: npm install
        working-directory: FrontAir

      - name: Verify node version
        run: node -v
        
      - name: Verify npm version
        run: npm -v

      - name: Linter
        run: npm run lint
        working-directory: FrontAir

#      - name: Run tests
#        run: npm run test
#        working-directory: FrontAir

      - name: Build the application
        run: npm run build-only
        working-directory: FrontAir

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

