name: Build & Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  DAY_OF_THE_WEEK: Monday

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Greeting: Hey

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Say Hey to Pepijn if it is Monday
        if: ${{ env.DAY_OF_THE_WEEK == 'Monday' }}
        run:  echo "$Greeting $First_Name, today is $DAY_OF_THE_WEEK!"
        env:
          First_Name: Pepijn

      - name: Install dependencies
        run: npm install
        working-directory: FrontAir

      - name: Verify node version
        run: node -v
        
      - name: Verify npm version
        run: npm -v

      - name: Linter
        run: npm run lint
        working-directory: FrontAir

#      - name: Run tests
#        run: npm run test
#        working-directory: FrontAir

      - name: Build the application
        run: npm run build-only
        working-directory: FrontAir

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
#          publish_dir: ./dist  # Path to the directory where the build is output


  release:
    runs-on: ubuntu-latest
    needs: build  # Only run this job if the build is successful
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Create a Tag
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          echo "Creating tag $TAG"
          git tag $TAG
          git push origin $TAG

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_creation.outputs.TAG }}  # Reference the created tag
          release_name: "Release ${{ steps.tag_creation.outputs.TAG }}"
          body: "Automated release of Vue.js application."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional Step: Upload build artifacts (dist folder) to the release
      - name: Upload build artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.zip  # You may zip your dist/ folder if necessary
          asset_name: dist.zip
          asset_content_type: application/zip
